name: the_bar_gym
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  js: ^0.6.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  google_fonts: ^2.1.0
  jiffy: ^4.1.0
  cached_network_image: ^3.1.0
  flutter_barcode_scanner: ^2.0.0
  qr_code_scanner: ^0.6.1
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


